### ISSUE TITLE
Test coverage changes in CI

### ISSUE THREAD

**Issue by synzen** [CSC59939/QuikBorrow#104]
we can have test coverage changes automatically shown if we use Coveralls in our CI pipeline

https://coveralls.io/
![image](https://user-images.githubusercontent.com/18688793/69299611-fd632580-0bde-11ea-86e1-4d0b613cb466.png)

or CodeCov

https://codecov.io/

![image](https://user-images.githubusercontent.com/18688793/69299584-e6243800-0bde-11ea-9582-5c82f7a3d704.png) 

which can also post comments with pretty graphs & stuff
![image](https://user-images.githubusercontent.com/18688793/69299651-14a21300-0bdf-11ea-8772-0e02303c01a3.png)

but @MicLi01 is the only one who can allow those tools access to the github repo since there can only be one repo owner

**Comment by MicLi01** [comment]
I took a look at it. I need the organization leader's approval(Nikolai) before I can add this in. Waiting for the request to be approved.

**Comment by synzen** [comment]
oo I see, gotcha
