### ISSUE TITLE
Option to document Mongoose models and API Routes with JSDoc

### ISSUE THREAD

**Issue by synzen** [CSC59939/QuikBorrow#62]
one option we can use to create documentation is to use [JSDoc](https://devdocs.io/jsdoc/) to auto-generate HTML documentation for our mongoose models and API routes - which can then be hosted by express as part of continuous deployment. derived from the JSDoc comments on https://github.com/CSC59939/QuickBorrow/blob/master/server/routes/api/users.js:

![image](https://user-images.githubusercontent.com/18688793/68639110-8ee0e200-04d1-11ea-8395-eed71559bbce.png)

the above is the default template - there are custom JSDoc templates we can use to make it very pretty: https://github.com/braintree/jsdoc-template

up to you guys though, just thought this would be cool :>

***
for anyone unfamiliar, the below is more of a guide:

on a unrelated note, the use of JSDoc also allows [IntelliSense](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2019) to know the variable types, which in turn helps the developer (especially when calling a function from another file):

Before (gertner's voice: **we have *no* idea what we're doing!**):
![image](https://user-images.githubusercontent.com/18688793/68639459-9fde2300-04d2-11ea-8509-2060c7333854.png)

![image](https://user-images.githubusercontent.com/18688793/68638951-1bd76b80-04d1-11ea-87a5-722006b60a42.png)

![image](https://user-images.githubusercontent.com/18688793/68638930-0bbf8c00-04d1-11ea-90bc-a248276236f3.png)

After (gertner: **very good, you are now best student**):
![image](https://user-images.githubusercontent.com/18688793/68639407-7a511980-04d2-11ea-88be-f06168982b2d.png)

![image](https://user-images.githubusercontent.com/18688793/68639391-6a393a00-04d2-11ea-9e5e-e735864dc385.png)

![image](https://user-images.githubusercontent.com/18688793/68639430-8937cc00-04d2-11ea-8c43-1dea8b7a40a9.png)

To easily create the comments, put your cursor above a function and
1. Type `/**`
![image](https://user-images.githubusercontent.com/18688793/68639682-53dfae00-04d3-11ea-8d9a-1165db5fc7dd.png)

2. Press Enter
![image](https://user-images.githubusercontent.com/18688793/68639701-5fcb7000-04d3-11ea-804f-9bd040879273.png)

**Comment by JackyLiu97** [comment]
Let's use JSDoc as part of the documentation. This is incredibly useful and will help us more when our project gets more complex.

**Comment by synzen** [comment]
I've looked at a lot of options in generating documentation but unfortunately everything seems to be missing one thing or another

### JSDoc built-in doc generator
Pros
- Great for generating documentation for classes, functions, methods (data) based on comments
- Has the added plus of no extra dependencies since jsdoc is already used to document code (at least for VS Code where it's built in for type-suggestions)

Cons
- Has absolutely no support for documenting APIs for request bodies, responses, urls, etc. We would have to do hacky workarounds for it to work

### apiDocs https://apidocjs.com/
Pros
- Visually OK at API documentation
- Built-in interface for API testing

Cons
- No easy way of documenting data (mongoose) models
- Somewhat frustrating to actually use because something things don't make sense in their syntax

### swagger-ui https://www.npmjs.com/package/swagger-ui-express (https://swagger.io/tools/swagger-ui/)
Pros
- Seems to be a popular standard way of documenting APIs
- Generates comprehensive docs

Cons
- __**SO**__ much overhead in learning things we don't need to, too much for a couple days
- Fixed visual themes from what I see (not that it matters for us)

### Postman API Generator https://learning.getpostman.com/docs/postman/api-documentation/intro-to-api-documentation/

Pros
- It's beautiful
- Excellent at writing out and testing API routes

Cons
- Limited in number of public views before it gets shut down (not that it matters for us)
- No documentation for data (mongoose) models
- Maybe just me but it's confusing as hell to navigate to generate the docs

---
Ideally, and probably what big companies do, we'd make our own API documentation. But since we only have a couple days, it's probably best to stick with github wikis
